services:
  mysql:
    image: mysql:8.0
    container_name: inventory-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=inventory
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: inventory-redis
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/inventory
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - JWT_SECRET=my-secret-key
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    restart: unless-stopped

volumes:
  db_data:
  redis_data: